#默认使用配置
server:
  port: 8080
spring:
  profiles:
    active: dev

  redis:
    host: localhost
    database: 0
    port: 6379
    password:


    jedis:
      pool:
        max-active: 8
        min-idle: 0
  activemq:
    user: admin
    password: admin
    broker-url:  tcp://127.0.0.1:61616
  jms:
    pub-sub-domain: false
  freemarker:
    allow-request-override: false
    charset: UTF-8
    check-template-location: true
    enabled: true
    suffix: .html
    template-loader-path: ["/WEB-INF/jsp/"]
    settings:
          default_encoding: UTF-8



queueName: publish.queue
topicName: publish.topic


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  #type-aliases-package: com.example.boot.model # 注意：对应实体类的路径
  mapper-locations: classpath:mapper/*.xml


#三个横线
logging:
  config: classpath:logback-spring.xml

---
#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource